### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by JeysonFlores** [giraffelibrary/giraffe#2]
Hello. I wanted to run the [hello world example](http://giraffelibrary.org/eg-gtk3-hello-world.html). I tried to install this library but I'm having problems running the Makefile.
What is the process of building this lib?
Thanks

**Comment by pclayton** [comment]
As soon as I can get my hands on an Ubuntu-like system, I'll have a look at the MLton issue.

For Poly/ML, I think there is an issue with the Ubuntu package: it should put `polyml.pc` somewhere in the system pkg-config path.  If it had done that, the command `pkg-config --libs polyml` wouldn't have failed.  The file lists of the Poly/ML amd64 packages for the latest release (hirsute) are
[polyml](https://packages.ubuntu.com/hirsute/amd64/polyml/filelist),
[libpolyml9](https://packages.ubuntu.com/hirsute/amd64/libpolyml9/filelist),
[libpolyml-dev](https://packages.ubuntu.com/hirsute/amd64/libpolyml-dev/filelist) and
[polyml-modules](https://packages.ubuntu.com/hirsute/amd64/polyml-modules/filelist).
Looking at these, none of them appear to provide `polyml.pc` so perhaps that is the issue.

To work around this, I think you will need to build Poly/ML yourself.  Use version 5.8.1 because there are some changes in 5.8.2, the latest, which need a new release of Giraffe Library.  It's actually very easy.  You can get version 5.8.1 on the [releases page](https://github.com/polyml/polyml/releases) and then follow the build instructions on the [download page](https://www.polyml.org/download.html).

**Comment by pclayton** [comment]
There are various books on SML.  Those I know of available online are:
  - [ML for the Working Programmer (2nd ed.)](https://www.cl.cam.ac.uk/~lp15/MLbook/), Lawrence C. Paulson
  - [Programming in Standard ML](http://www.cs.cmu.edu/~rwh/isml/book.pdf), Robert Harper
  - [Unix System Programming with Standard ML](http://mlton.org/References.attachments/Shipman02.pdf), Anthony L. Shipman

The SML/NJ site has a useful secton on [SML literature](https://www.smlnj.org/doc/literature.html), which includes many books and tutorials.  You should be wary of literature that pre-dates 1997 because it will be using the older version of the language SML90, which has some significant differences especially to the module system.

There are various resources linked from the [Github Project](https://smlfamily.github.io/) including a [context-free grammar](https://people.mpi-sws.org/~rossberg/sml.html) and the [Basis Library](https://smlfamily.github.io/Basis/index.html).

Good luck, and enjoy!

**Comment by pclayton** [comment]
When developing with Giraffe Library, one benefit of Poly/ML is that it supports incremental compilation.  The Makefile used in the examples saves the state after the library code is compiled so that it does not need to be recompiled each time you build your application.  MLton is a whole program optimizing compiler and, by design, does not support incremental compilation.  Unfortunately, this can lead to longer build times and slower iteration in development.  When developing, I build with Poly/ML first, which quickly finds any syntax/type errors, and set MLton compiling in the background.  It is worth reading the section on issues at the bottom of the page on [Building with MLton](http://giraffelibrary.org/ug-building-mlton.html).

**Comment by JeysonFlores** [comment]
Btw. I wanted to set a label with a text in Spanish, it didn't work because it seems that SML doesn't support Unicode by default. However it seems that if I put Unicode characters in the `.ui` file it can run without problems. Do you have any recommendations about how to effectively manipulate Unicode characters in SML and Giraffe?

**Comment by pclayton** [comment]
Glad you found a way.  I'll answer anyway, in case it's useful for you or anyone else.

[GTK uses Unicode for all strings, encoded using UTF-8](https://developer-old.gnome.org/gtk3/stable/gtk-question-index.html#id-1.2.5.3.3.1.9), so one option, as you observe, is to just write the label in Spanish using a UTF-8 encoded string.  Sadly, the current Unicode support in SML is non-existent as the language hasn't been updated since 1997.  The Basis Library has barely changed either.  Still, a string in SML can contain any sequence of bytes, so a string can contain UTF-8 encoded text.  However, you would have to write string literals in the UTF-8 encoding, e.g.
```
"\208\159\209\128\208\184\208\178\208\181\209\130, \208\188\208\184\209\128!\n"
```
instead of
```
"Привет, мир!\n"
```
which is a non-starter in practice.  Also, some operations in the String structure don't work for UTF-8 encoded text, as noted in the [SML Interface](http://giraffelibrary.org/ug-types.html#utf8-filename-types), e.g. `String.size` will return the number of bytes, not the number of characters.  MLton has an extension to allow UTF-8 encoded string literals which is enabled by compiling code in the scope of the annotation `allowExtendedTextConsts true`.  However, this code won't port of Poly/ML, but it may be possible to support such string literals by creating a new REPL using `[PolyML.compiler](https://www.polyml.org/documentation/Reference/PolyMLStructure.html#compiler)` whose reader transforms string literals.

An alternative approach is to use [gettext](https://www.gnu.org/software/gettext/manual/gettext.html) to internationalize your application.  The code wraps each string literal with a call to `gettext` (or variant) which will substitute the string with a translation based on the locale environment variables at run time (one of LC_ALL, LC_MESSAGES, LANG).  With this approach, the code would contain just valid SML strings for the message id and the Unicode translations would be in the PO files.  Unfortunately, I don't know of any bindings to the libintl functions (except some GLib wrappers provided with Giraffe Library, e.g. `GLib.dgettext`), nor the locale functions.  (In the case of the latter, it looks like some thought was given to including locale functions in the Basis Library, as there appears to be a [draft structure Locale](https://www.cs.princeton.edu/~appel/smlnj/basis/locale.html), but that didn't make it into the final version.)  I suspect `xgettext` won't be usable on SML source code either.  Still, I'll try to produce an example of this approach.
